"""
We're going to calculate the probability that a certain coset is
correct, given a syndrome, by brute force.
This is a subroutine for RG decoding, and it can be used to generate
training data for the NN.  
"""

import numpy as np, itertools as it#, circuit_metric as cm
import sparse_pauli as sp
from functools import reduce
from operator import mul, or_ as union, xor as sym_diff
from scipy.special import betainc
import SCLayoutClass as SCLayoutClass
import decoding_2d as dc

#from the itertools cookbook
def powerset(iterable):
    "powerset([1,2,3]) --> () (1,) (2,) (3,) (1,2) (1,3) (2,3) (1,2,3)"
    s = list(iterable)
    return it.chain.from_iterable(it.combinations(s, r) for r in range(len(s)+1))

def weight_dist(stab_gens, identity, log, coset_rep, ltr='x'):
    """
    If we iterate over an entire stabiliser group, we can calculate
    the weight of each Pauli of the form c * l * s for c a coset
    representative for the normaliser of the stabiliser, l a choice of 
    logical operator, and s a stabiliser.
    Colloquially, c is generated by a one-to-one map from the
    syndromes.

    The weight will range from 0 to nq, where nq is the number of
    qubits in the system, and there'll be many Paulis with each weight.
    Therefore, we return an array full of counts.

    For speed, I do the set sym_diffs directly   
    """

    # First get nq
    nq = len(reduce(union, (s.support() for s in stab_gens)))

    wt_counts_I = np.zeros((nq + 1,), dtype=np.int_)
    wt_counts_L = np.zeros((nq + 1,), dtype=np.int_)
    
    # i = 0
    # TODO Strip single set and do sym_diff instead of mul

    # for subset in powerset(stab_gens):
    #     i += 1
    #     s = reduce(mul, subset, sp.Pauli())
    #     wt_counts_I[(s * identity * coset_rep).weight()] += 1
    #     wt_counts_L[(s * log * coset_rep).weight()] += 1
    #     #if i % 1000 == 0:
    #     #    print(i)
    
    ltr = ltr.lower()
    if ltr == 'x':
        bare_sets = [gen.x_set for gen in stab_gens]
        coset_rep_set = coset_rep.x_set
        log_coset_rep_set = log.x_set ^ coset_rep.x_set
    elif ltr == 'z':
        bare_sets = [gen.z_set for gen in stab_gens]
        coset_rep_set = coset_rep.z_set
        log_coset_rep_set = log.z_set ^ coset_rep.z_set
    
    for subset in powerset(bare_sets):
        s = reduce(sym_diff, subset, set())
        wt_counts_I[len(s ^ coset_rep_set)] += 1
        wt_counts_L[len(s ^ log_coset_rep_set)] += 1

    return [wt_counts_I, wt_counts_L]

def prob_integral(weight_counts, p_lo, p_hi):
    """
    The probability of a logical out given a syndrome coset rep in is
    sum_{s in stab_group} (p/(1-p))^{|c * l * s|} where c is the coset
    rep, and l is the logical.
    We're going to sample p over a uniform distribution from p_lo to
    p_hi, so we calculate the expected value of this probability over
    the distribution.
    """
    n = len(weight_counts) - 1
    return sum([
                    c * (betainc(w + 1, n - w + 1, p_hi) 
                        - betainc(w + 1, n - w + 1, p_lo))
                    for w, c in enumerate(weight_counts)
                ])/(p_hi - p_lo)

def single_prob(weight_counts, p):
    """
    For debugging purposes, I'd like to have a function that evaluates
    the coset probability at a single point in p-space, so that I can
    see whether the integral is off. This is going to get normalised
    anyway, so we can output probabilities that are off by an overall
    factor of (1 - p) ** n.
    """

    return [sum([ c * (p / (1. - p)) ** w for w, c in enumerate(weight_counts[0])]), 
	        sum([ c * (p / (1. - p)) ** w for w, c in enumerate(weight_counts[1])])]

def coset_prob(stab_gens, log, coset_rep, p_lo, p_hi):
    return prob_integral(weight_dist(stab_gens, log, coset_rep), p_lo, p_hi)

if __name__ == '__main__':
    distance = 5
    x_anc_len = 12
    #test_layout = cm.SCLayoutClass.SCLayout(5)
    test_layout = SCLayoutClass.SCLayout(distance)
    x_stabs = list(test_layout.stabilisers()['X'].values())
    log = test_layout.logicals()[0]
    sim_test = dc.Sim2D(distance, 0.01) # probability is irrelevant since we provide directly the error
    lst = []
    z_ancs_keys = list(sim_test.layout.z_ancs())
    cycles = 0
    store_s = []
    rd = [sp.Pauli([],[]), sp.Pauli([2],[]), sp.Pauli([3],[]), sp.Pauli([4],[]), sp.Pauli([5],[]), sp.Pauli([6],[]), sp.Pauli([12],[]), sp.Pauli([13], []), 
           sp.Pauli([14],[]), sp.Pauli([15],[]), sp.Pauli([16],[]), sp.Pauli([22],[]), sp.Pauli([23],[]), sp.Pauli([24], []), sp.Pauli([25],[]), 
           sp.Pauli([26],[]), sp.Pauli([32],[]), sp.Pauli([33],[]), sp.Pauli([34],[]), sp.Pauli([35], []), sp.Pauli([36],[]), sp.Pauli([42],[]), 
           sp.Pauli([43],[]), sp.Pauli([44],[]), sp.Pauli([45],[]), sp.Pauli([46], []), sp.Pauli([2,3],[]), sp.Pauli([2,4],[]), sp.Pauli([2,5],[]), 
           sp.Pauli([2,6],[]), sp.Pauli([2,12],[]), sp.Pauli([2,13], []), sp.Pauli([2,14],[]), sp.Pauli([2,15],[]), sp.Pauli([2,16],[]), sp.Pauli([2,22],[]), 
           sp.Pauli([2,23],[]), sp.Pauli([2,24], []), sp.Pauli([2,25],[]), sp.Pauli([2,26],[]), sp.Pauli([2,32],[]), sp.Pauli([2,33],[]), sp.Pauli([2,34],[]),
           sp.Pauli([2,35], []), sp.Pauli([2,36],[]), sp.Pauli([2,42],[]), sp.Pauli([2,43],[]), sp.Pauli([2,44],[]), sp.Pauli([2,45],[]),
           sp.Pauli([2,46], []), sp.Pauli([3, 4], []), sp.Pauli([3, 5], []), sp.Pauli([3, 6], []), sp.Pauli([3, 12], []), sp.Pauli([3, 13], []), 
           sp.Pauli([3, 14], []), sp.Pauli([3, 15], []), sp.Pauli([3, 16], []), sp.Pauli([3, 22], []), sp.Pauli([3, 23], []),
           sp.Pauli([3, 24], []), sp.Pauli([3, 25], []), sp.Pauli([3, 26], []), sp.Pauli([3, 32], []), sp.Pauli([3, 33], []), sp.Pauli([3, 34], []),
           sp.Pauli([3, 35], []), sp.Pauli([3, 36], []), sp.Pauli([3, 42], []), sp.Pauli([3, 43], []), sp.Pauli([3, 44], []), sp.Pauli([3, 45], []),
           sp.Pauli([3, 46], []), sp.Pauli([4, 5], []), sp.Pauli([4, 6], []), sp.Pauli([4, 12], []), sp.Pauli([4, 13], []), sp.Pauli([4, 14], []), 
           sp.Pauli([4, 15], []), sp.Pauli([4, 16], []), sp.Pauli([4, 22], []), sp.Pauli([4, 23], []), sp.Pauli([4, 24], []), sp.Pauli([4, 25], []), 
           sp.Pauli([4, 26], []), sp.Pauli([4, 32], []), sp.Pauli([4, 33], []), sp.Pauli([4, 34], []), sp.Pauli([4, 35], []), sp.Pauli([4, 36], []), 
           sp.Pauli([4, 42], []), sp.Pauli([4, 43], []), sp.Pauli([4, 44], []), sp.Pauli([4, 45], []), sp.Pauli([4, 46], []), sp.Pauli([5, 6], []), 
           sp.Pauli([5, 12], []), sp.Pauli([5, 13], []), sp.Pauli([5, 14], []), sp.Pauli([5, 15], []), sp.Pauli([5, 16], []), sp.Pauli([5, 22], []), 
           sp.Pauli([5, 23], []), sp.Pauli([5, 24], []), sp.Pauli([5, 25], []), sp.Pauli([5, 26], []), sp.Pauli([5, 32], []), sp.Pauli([5, 33], []), 
           sp.Pauli([5, 34], []), sp.Pauli([5, 35], []), sp.Pauli([5, 36], []), sp.Pauli([5, 42], []), sp.Pauli([5, 43], []), sp.Pauli([5, 44], []), 
           sp.Pauli([5, 45], []), sp.Pauli([5, 46], []), sp.Pauli([6, 12], []), sp.Pauli([6, 13], []), sp.Pauli([6, 14], []), sp.Pauli([6, 15], []), 
           sp.Pauli([6, 16], []), sp.Pauli([6, 22], []), sp.Pauli([6, 23], []), sp.Pauli([6, 24], []), sp.Pauli([6, 25], []), sp.Pauli([6, 26], []), 
           sp.Pauli([6, 32], []), sp.Pauli([6, 33], []), sp.Pauli([6, 34], []), sp.Pauli([6, 35], []), sp.Pauli([6, 36], []), sp.Pauli([6, 42], []), 
           sp.Pauli([6, 43], []), sp.Pauli([6, 44], []), sp.Pauli([6, 45], []), sp.Pauli([6, 46], []), sp.Pauli([12, 13], []), sp.Pauli([12, 14], []), 
           sp.Pauli([12, 15], []), sp.Pauli([12, 16], []), sp.Pauli([12, 22], []), sp.Pauli([12, 23], []), sp.Pauli([12, 24], []), sp.Pauli([12, 25], []), 
           sp.Pauli([12, 26], []), sp.Pauli([12, 32], []), sp.Pauli([12, 33], []), sp.Pauli([12, 34], []), sp.Pauli([12, 35], []), sp.Pauli([12, 36], []), 
           sp.Pauli([12, 42], []), sp.Pauli([12, 43], []), sp.Pauli([12, 44], []), sp.Pauli([12, 45], []), sp.Pauli([12, 46], []), sp.Pauli([13, 14], []), 
           sp.Pauli([13, 15], []), sp.Pauli([13, 16], []), sp.Pauli([13, 22], []), sp.Pauli([13, 23], []), sp.Pauli([13, 24], []), sp.Pauli([13, 25], []), 
           sp.Pauli([13, 26], []), sp.Pauli([13, 32], []), sp.Pauli([13, 33], []), sp.Pauli([13, 34], []), sp.Pauli([13, 35], []), sp.Pauli([13, 36], []), 
           sp.Pauli([13, 42], []), sp.Pauli([13, 43], []), sp.Pauli([13, 44], []), sp.Pauli([13, 45], []), sp.Pauli([13, 46], []), sp.Pauli([14, 15], []), 
           sp.Pauli([14, 16], []), sp.Pauli([14, 22], []), sp.Pauli([14, 23], []), sp.Pauli([14, 24], []), sp.Pauli([14, 25], []), sp.Pauli([14, 26], []), 
           sp.Pauli([14, 32], []), sp.Pauli([14, 33], []), sp.Pauli([14, 34], []), sp.Pauli([14, 35], []), sp.Pauli([14, 36], []), sp.Pauli([14, 42], []), 
           sp.Pauli([14, 43], []), sp.Pauli([14, 44], []), sp.Pauli([14, 45], []), sp.Pauli([14, 46], []), sp.Pauli([15, 16], []), sp.Pauli([15, 22], []), 
           sp.Pauli([15, 23], []), sp.Pauli([15, 24], []), sp.Pauli([15, 25], []), sp.Pauli([15, 26], []), sp.Pauli([15, 32], []), sp.Pauli([15, 33], []),
           sp.Pauli([15, 34], []), sp.Pauli([15, 35], []), sp.Pauli([15, 36], []), sp.Pauli([15, 42], []), sp.Pauli([15, 43], []), sp.Pauli([15, 44], []), 
           sp.Pauli([15, 45], []), sp.Pauli([15, 46], []), sp.Pauli([16, 22], []), sp.Pauli([16, 23], []), sp.Pauli([16, 24], []), sp.Pauli([16, 25], []), 
           sp.Pauli([16, 26], []), sp.Pauli([16, 32], []), sp.Pauli([16, 33], []), sp.Pauli([16, 34], []), sp.Pauli([16, 35], []), sp.Pauli([16, 36], []), 
           sp.Pauli([16, 42], []), sp.Pauli([16, 43], []), sp.Pauli([16, 44], []), sp.Pauli([16, 45], []), sp.Pauli([16, 46], []), sp.Pauli([22, 23], []),
           sp.Pauli([22, 24], []), sp.Pauli([22, 25], []), sp.Pauli([22, 26], []), sp.Pauli([22, 32], []), sp.Pauli([22, 33], []), sp.Pauli([22, 34], []),
           sp.Pauli([22, 35], []), sp.Pauli([22, 36], []), sp.Pauli([22, 42], []), sp.Pauli([22, 43], []), sp.Pauli([22, 44], []), sp.Pauli([22, 45], []),
           sp.Pauli([22, 46], []), sp.Pauli([23, 24], []), sp.Pauli([23, 25], []), sp.Pauli([23, 26], []), sp.Pauli([23, 32], []), sp.Pauli([23, 33], []), 
           sp.Pauli([23, 34], []), sp.Pauli([23, 35], []), sp.Pauli([23, 36], []), sp.Pauli([23, 42], []), sp.Pauli([23, 43], []), sp.Pauli([23, 44], []), 
           sp.Pauli([23, 45], []), sp.Pauli([23, 46], []), sp.Pauli([24, 25], []), sp.Pauli([24, 26], []), sp.Pauli([24, 32], []), sp.Pauli([24, 33], []), 
           sp.Pauli([24, 34], []), sp.Pauli([24, 35], []), sp.Pauli([24, 36], []), sp.Pauli([24, 42], []), sp.Pauli([24, 43], []), sp.Pauli([24, 44], []), 
           sp.Pauli([24, 45], []), sp.Pauli([24, 46], []), sp.Pauli([25, 26], []), sp.Pauli([25, 32], []), sp.Pauli([25, 33], []), sp.Pauli([25, 34], []),
           sp.Pauli([25, 35], []), sp.Pauli([25, 36], []), sp.Pauli([25, 42], []), sp.Pauli([25, 43], []), sp.Pauli([25, 44], []), sp.Pauli([25, 45], []),
           sp.Pauli([25, 46], []), sp.Pauli([26, 32], []), sp.Pauli([26, 33], []), sp.Pauli([26, 34], []), sp.Pauli([26, 35], []), sp.Pauli([26, 36], []), 
           sp.Pauli([26, 42], []), sp.Pauli([26, 43], []), sp.Pauli([26, 44], []), sp.Pauli([26, 45], []), sp.Pauli([26, 46], []), sp.Pauli([32, 33], []), 
           sp.Pauli([32, 34], []), sp.Pauli([32, 35], []), sp.Pauli([32, 36], []), sp.Pauli([32, 42], []), sp.Pauli([32, 43], []), sp.Pauli([32, 44], []), 
           sp.Pauli([32, 45], []), sp.Pauli([32, 46], []), sp.Pauli([33, 34], []), sp.Pauli([33, 35], []), sp.Pauli([33, 36], []), sp.Pauli([33, 42], []), 
           sp.Pauli([33, 43], []), sp.Pauli([33, 44], []), sp.Pauli([33, 45], []), sp.Pauli([33, 46], []), sp.Pauli([34, 35], []), sp.Pauli([34, 36], []), 
           sp.Pauli([34, 42], []), sp.Pauli([34, 43], []), sp.Pauli([34, 44], []), sp.Pauli([34, 45], []), sp.Pauli([34, 46], []), sp.Pauli([35, 36], []), 
           sp.Pauli([35, 42], []), sp.Pauli([35, 43], []), sp.Pauli([35, 44], []), sp.Pauli([35, 45], []), sp.Pauli([35, 46], []), sp.Pauli([36, 42], []), 
           sp.Pauli([36, 43], []), sp.Pauli([36, 44], []), sp.Pauli([36, 45], []), sp.Pauli([36, 46], []), sp.Pauli([42, 43], []), sp.Pauli([42, 44], []), 
           sp.Pauli([42, 45], []), sp.Pauli([42, 46], []), sp.Pauli([43, 44], []), sp.Pauli([43, 45], []), sp.Pauli([43, 46], []), sp.Pauli([44, 45], []),
           sp.Pauli([44, 46], []),sp.Pauli([45,46], [])]
    #while len(lst) < 500:
    for e in range(len(rd)):
        cycles += 1
        #rnd_err = sim_test.random_error()
        rnd_err = rd[e]
        #print(rnd_err)
        synds = sim_test.syndromes(rnd_err)
        #print(synds[1])
        dumb_x_corr, dumb_z_corr = sim_test.dumb_correction(synds)
        coset_rep = dumb_x_corr     #sp.Pauli({5,13,22,26,33,42,46},{})
        prob_dist = single_prob(weight_dist(x_stabs, sp.Pauli(), log, coset_rep), 0.01)
        #single_prob(weight_dist(x_stabs, coset_rep), 0.01)       
        norm = sum(prob_dist)
        prob_dist = [p / norm for p in prob_dist]
        
        list_z = [0] * len(z_ancs_keys)
        for k in synds[1]:
            key = sim_test.layout.map.inv[k]
            pos = z_ancs_keys.index(key)
            list_z[pos] = 1
        
        s = ''
        for i in range(x_anc_len):
            s += str(list_z[i])
		
        if s not in store_s:
            store_s.append(s)
            lst.append([s, prob_dist])

        if cycles % 20 == 0:
            print(len(lst), cycles)
            #print('store_s ', store_s)
    
    for i in range(len(lst)):
        print(lst[i])

#---------------------------------------------------------------------#