import decoding_2d as dc2 
import decoding_3d as dc3 

def circuit_syndrome_test():
    """
    compares syndromes generated by measurement circuit with q = 0 to
    those generated by perfect stabiliser measurement from 2D
    simulation. 
    They all ought to match.
    """
    two_d_sim = dc2.Sim2D(15, 15, 0.00)
    three_d_sim = dc3.Sim3D(15, 1000, ('pq', 0.1, 0.0))
    err_hist, synd_hist = three_d_sim.history()

    for idx, err in enumerate(err_hist):
        idl_x_synd, idl_z_synd = two_d_sim.syndromes(err)
        assert synd_hist['X'][idx] == set(idl_x_synd)
        assert synd_hist['Z'][idx] == set(idl_z_synd)